### PR TITLE
Cleaned the code Structure

### PR DESCRIPTION
**Pull request by Samad999777**
Moved the Js Code from index html to another folder and removed the console log for modal & made a small function for the button onClick() as well

### CODE REVIEW

**Comment by JustinGOSSES** [comment]
Thanks for the attempted pull request @Samad999777  However, it looks like you ended up taking out the URL redirect JavaScript scripts at the bottom. These are important to maintain.

**Comment by Samad999777** [comment]
Let me review these again

**Comment by Samad999777** [comment]
@jasonduley Thanks for your response  The redirect js code is not removed, I have linked them through an external file 
in my pull request line 431 <script src="index_page_scripts/to_data_vis_page.js"></script>
This linked script contains the redirect code and its working. Can you kindly confirm?

**Comment by Samad999777** [comment]
@JustinGOSSES do I still need to make a new pull request ?

**Pull request closed without merging**
